server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8088
          predicates:
            - Path=/clients/**
        - id: r2
          uri: http://localhost:8088
          predicates:
            - Path=/client/**
